// <auto-generated />
using BezpiecznyZgranyBudzet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BezpiecznyZgranyBudzet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251206222902_db_init")]
    partial class db_init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinanceData", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<decimal>("BrakujacaKwota2026")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Budzet")
                        .HasColumnType("numeric");

                    b.Property<string>("BudzetZadaniowy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BudzetZadaniowyPelny")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CzescBudzetowa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DotacjaZKim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DysponentSrodkow")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Dzial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GrupaWydatkow")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KomorkaOrganizacyjna")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("KwotaUmowy")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Limit2026")
                        .HasColumnType("numeric");

                    b.Property<string>("NazwaProgramu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NazwaZadania")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NrUmowy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Paragraf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PlanWI")
                        .HasColumnType("numeric");

                    b.Property<string>("PodstawaPrawnaDotacji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Potrzeby2026")
                        .HasColumnType("numeric");

                    b.Property<string>("Przeznaczenie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rozdzial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SzczegoloweUzasadnienie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uwagi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZrodloFinansowania")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FinanceData");
                });
#pragma warning restore 612, 618
        }
    }
}
